### ISSUE TITLE
Few parameters in the 'set' cmd accepts empty input.

### ISSUE THREAD

**Issue by sureshanaparti** [apache/cloudstack-cloudmonkey#100]
Few parameters (secretkey, apikey, url, etc) in the 'set' cmd accepts empty input, and doesn't prompt as invalid input. It also update them as empty in the config file.

Any way (or command) to check the apikey, secretkey, timeout, etc configured, without checking the profile.

```
(cloudcmk) > set secretkey 
(cloudcmk) > 
(cloudcmk) > set apikey 
(cloudcmk) > 
(cloudcmk) > set timeout 
Error caught while setting timeout: strconv.Atoi: parsing "": invalid syntax
(cloudcmk) > 
(cloudcmk) > set url
(cloudcmk) >
(cloudcmk) > set username
(cloudcmk) > 
(cloudcmk) > set password
(cloudcmk) >  
(cloudcmk) > set domain
(cloudcmk) >
(cloudcmk) > set profile
Loaded in-built API cache. Failed to read API cache, please run 'sync'.
Loaded server profile: 
Url:         
Username:    
Domain:      
API Key:     
Total APIs:  590

() > 
```

The config file entires of the profile, updated to =>

```
[cloudcmk]
url       =
username  =
password  =
domain    =
apikey    =
secretkey =
```

**Comment by rhtyd** [comment]
I think these are not regressions warranting a new RC1. Can you check @sureshanaparti if they're regression/blockers or bugs?

**Comment by Pearl1594** [comment]
It isn't a regression. Has always behaved this way. Yes, it surely needs fixing - but isn't a blocker either. coz one could reset the value to the right one and it works fine

**Comment by sureshanaparti** [comment]
> I think these are not regressions warranting a new RC1. Can you check @sureshanaparti if they're regression/blockers or bugs?

Not a regression @rhtyd

**Comment by sureshanaparti** [comment]
> It isn't a regression. Has always behaved this way. Yes, it surely needs fixing - but it isn't a blocker, as one could reset the value to the right one and it works fine. Also, api/secret keys can be empty if username and password are provided

Agree with api/secret keys, that can be empty, other configs are also set to empty. Updated description.
