### ISSUE TITLE
How to resolve delete trafficmonitor Error message

### ISSUE THREAD

**Issue by cdaehyun0** [apache/cloudstack-cloudmonkey#105]
CloudMonkey 6.1.0.
Error Message:::::::

(localcloud) 🐱 > delete trafficmonitor id=2f3710d4-04af-412b-a64a-1aca0cb07c58
🙈 Error: (HTTP 530, error code 4250) Host 2f3710d4-04af-412b-a64a-1aca0cb07c58 cannot be deleted as it is not in maintenance mode. Either put the host into maintenance or perform a forced deletion.

How can I resolve this issue?

**Comment by cdaehyun0** [comment]
> 
> 
> @cdaehyun0, you have to put the host into maintenance mode. The message, in your case, is misleading because there isn't an API param `force` in the `deleteTrafficMonitor` call.
> 
> `prepare hostformaintenance id=2f3710d4-04af-412b-a64a-1aca0cb07c58`

as you instructed, I ran the comand >>>  prepare hostformaintenance id=2f3710d4-04af-412b-a64a-1aca0cb07c58

It was generated Async API error message ....

jobstatus = 2for async API result 50) Host 2f3710d4-04af-412b-a64a-1aca0cb07c58 cannot be deleted as it is not
jobprocstatus = 0async API result  a forced deletion.
jobresultcode = 530ync API result aintenance id=2f3710d4-04af-412b-a64a-1aca0cb07c58
jobresult = map[errorcode:530 errortext:Command failed due to Internal Server Error]
jobinstancetype = Host
accountid = 7202d846-0c99-11ec-b5d8-66fb7da11fa2
cmd = org.apache.cloudstack.api.command.admin.host.PrepareForMaintenanceCmd
jobresulttype = object
jobinstanceid = 2f3710d4-04af-412b-a64a-1aca0cb07c58
created = 2021-10-07T14:56:44+0900
completed = 2021-10-07T14:56:44+0900
jobid = 0be9d5cb-6ff5-48cb-a66c-3d903e2e7dd7                                                                   jobprocstatus = 0
jobresultcode = 530ync API result
jobresult = map[errorcode:530 errortext:Command failed due to Internal Server Error]
jobinstancetype = Host API result  0be9d5cb-6ff5-48cb-a66c-3d903e2e7dd7
accountid = 7202d846-0c99-11ec-b5d8-66fb7da11fa22f3710d4-04af-412b-a64a-1aca0cb07c58
userid = 7204b736-0c99-11ec-b5d8-66fb7da11fa2
cmd = org.apache.cloudstack.api.command.admin.host.PrepareForMaintenanceCmd
jobstatus = 2
created = 2021-10-07T14:57:44+0900
completed = 2021-10-07T14:57:44+0900
jobid = ea85664b-cedc-458e-bdf3-08bc79b56f1c
jobresulttype = object
jobinstanceid = 2f3710d4-04af-412b-a64a-1aca0cb07c58
+
+
🙈 Error: async API failed for job ea85664b-cedc-458e-bdf3-08bc79b56f1c
(localcloud) 🐱 >

**Comment by rohityadavcloud** [comment]
Closing on the remark, that the issue/exception is from cloudstack and not cmk - so the bug must be reported and fixed in CloudStack (if it's not already resolved/fixed). Thanks.
