### ISSUE TITLE
Comma in csv output not wrapped in double quotes

### ISSUE THREAD

**Issue by pxn** [apache/cloudstack-cloudmonkey#106]
When command output field text contains `,` it breaks csv structure. Those fields should be enclosed in "".

output in JSON:

`() cmk > list virtualmachines `filter=name,displayname,instancename`
`{
  "count": 1,
  "virtualmachine": [
    {
      "displayname": "DuVPC-AD,WSUS, DNS",
      "instancename": "i-211-1313-VM",
      "name": "MS-DC-PRI"
    }
  ]
}`
 
same VM output in csv:
`() cmk > list virtualmachines filter=name,displayname,instancename`
`name,displayname,instancename`
`MS-DC-PRI,DuVPC-AD,WSUS, DNS,i-211-1313-VM`

expected csv output:
`() cmk > list virtualmachines filter=name,displayname,instancename`
`name,displayname,instancename`
`MS-DC-PRI,"DuVPC-AD,WSUS, DNS",i-211-1313-VM`

CloudMonkey 6.2.0 release.

**Comment by DaanHoogland** [comment]
fixed in #107
