### ISSUE TITLE
associatednetworkid= does not autocomplete

### ISSUE THREAD

**Issue by alexandremattioli** [apache/cloudstack-cloudmonkey#118]
When creating a shared network using an offering which has the SpecifyVLAN option set the associatednetworkid= should be able to autocomplete with the networks of that domain/account

**Comment by borisstoyanov** [comment]
@alexandremattioli can you give an example prompt with cmk please. From what I see you want it to look for associatednetworkid, but there is no such API listAssociatedNetworks, so I think this improvement is not achievable at the moment?

**Comment by alexandremattioli** [comment]
@borisstoyanov  it actually should list just the networks available, so network being created can be associated to one of them. It's just a "list networks"

**Comment by borisstoyanov** [comment]
@DaanHoogland can this correlate with #72 then?

**Comment by DaanHoogland** [comment]
yes, @borisstoyanov . it is bot about more intelligent autocompletion. This one to recognise the noun to use a list call for, and the aother one to add more specific arguments to the list command.

**Comment by borisstoyanov** [comment]
@rohityadavcloud advised this could be a small one, he's open to advise the assignee

**Comment by rohityadavcloud** [comment]
If the default heuristic isn't working, in the autocompletion code we can use a specific API for specific param that fixes this issue. cc @nvazquez there are existing examples with list templates etc I think in the codebase.
