### ISSUE TITLE
Migrate to Github Actions

### ISSUE THREAD

**Issue by rohityadavcloud** [apache/cloudstack-cloudmonkey#120]
Migrate from Travis to Github Actions
with @rahulbcn27

Refer:
https://github.com/apache/cloudstack-cloudmonkey/blob/main/.travis.yml
https://docs.github.com/en/actions/migrating-to-github-actions/migrating-from-travis-ci-to-github-actions

**Comment by rahulbcn27** [comment]
Thanks @rohityadavcloud . Looking into it.

**Comment by rahulbcn27** [comment]
https://github.com/apache/cloudstack-cloudmonkey/pull/121
