### ISSUE TITLE
Allow cmk to pass * as parameter value

### ISSUE THREAD

**Issue by rohityadavcloud** [apache/cloudstack-cloudmonkey#128]
In some APIs, the value * isn't encoded properly (for example, setting up global setting values). This has been fixed for the cloudstack-go SDK here: https://github.com/apache/cloudstack-go/pull/52

We should look at changes on https://github.com/apache/cloudstack-go/pull/52/files#diff-866d8df59b9cf9a2319595a38dd83789af4cc7666722d1fde09c1b9e7816bfd2R543 to encode the params at correctly https://github.com/apache/cloudstack-cloudmonkey/blob/main/cmd/network.go#L194 for such cases.

**Comment by davidjumani** [comment]
Hi @rohityadavcloud Could you please provide an example ? I tried createing a user / account with `*` in the name as well as updating a global setting with `*` in the value and the result was as expected

**Comment by rohityadavcloud** [comment]
@davidjumani can you check https://github.com/apache/cloudstack-go/pull/52 and for testing just pass * as value to the global setting both in cli and via shell script to cmk.
