### ISSUE TITLE
Missing prompt characters

### ISSUE THREAD

**Issue by NuxRo** [apache/cloudstack-cloudmonkey#14]
There seems to be some missing character in my shell (MATE terminal) at the prompt. Probably the infamous emoji?
![selection_359](https://user-images.githubusercontent.com/2357012/38824592-ac31826e-41a1-11e8-82f1-b9e7e8542249.png)

**Comment by rhtyd** [comment]
@NuxRo Yes, that's the emoji. In newer distros, they will support unicode emojis. You can try this https://victor.kropp.name/blog/emoji-on-linux/

I'll add support for custom prompt soon.

**Comment by rhtyd** [comment]
@NuxRo I've added support to add custom prompt and restricted the default prompt to same as the old cloudmonkey. The random emoji fun feature is implemented only when prompt is set to `random`. I'll publish new binaries soon, meanwhile you can build master from source if you want.
