### ISSUE TITLE
In CLI mode getting error: failed to authenticate, please check the credentials

### ISSUE THREAD

**Issue by AbdulShariff** [apache/cloudstack-cloudmonkey#141]
In cli mode when i try to login to cloudmonkey using any profile i get authentication issue.
After using commands set profile and sync i get this error:-
Error: failed to authenticate, please check the credentials.Can some one please help

**Comment by rohityadavcloud** [comment]
Have you set the right username, password and url? You can do: ‘set debug true’ if you’re still getting the error after setting the right credentials.

**Comment by rohityadavcloud** [comment]
@AbdulShariff any comments?

**Comment by rohityadavcloud** [comment]
Kindly reopen if there's more input on reproducing the issue.
