### ISSUE TITLE
How to run a cross-platform build?

### ISSUE THREAD

**Issue by synergiator** [apache/cloudstack-cloudmonkey#142]
AFAIK Golang is capable of creating a cross compilation as one-shot run.

Is it possible to take the main branch and use e.g. official Golang Docker container to create a Windows executable?

**Comment by rohityadavcloud** [comment]
Hi @synergiator that's correct, our build script uses go on whatever platform to build Windows executable: https://github.com/apache/cloudstack-cloudmonkey/blob/main/Makefile#L62

You can run `make all` and get the platform specific binaries from the dist directory when building from source code - https://github.com/apache/cloudstack-cloudmonkey#development

Hope that answers your question, if it doesn't and you've any issue to report you may re-open the ticket. Thanks.

**Comment by synergiator** [comment]
@rohityadavcloud thank you - I see now my problem. For some reason, I thought, that "make all" would include also Windows distributables.

However, for that purpose I had to type:

```
make dist
```

**Comment by rohityadavcloud** [comment]
Thanks @synergiator - I've updated the README now https://github.com/apache/cloudstack-cloudmonkey/blob/main/README.md#development to advise on `make dist`
