### ISSUE TITLE
6.4.0 add host -> authentication error

### ISSUE THREAD

**Issue by hoogenm** [apache/cloudstack-cloudmonkey#151]
With version 6.4.0, if I do `add host`, I get a credentials error from the api.
I tried cmk version 6.3.0 instead: version 6.3.0 did not result in an API error.

I tried version 6.3.0 because there seems to be a change after 6.3.0 in how get/post requests are made if a `password` param is included. I hope this helps.

**Comment by rohityadavcloud** [comment]
@hoogenm it's been fixed now - https://github.com/apache/cloudstack-cloudmonkey/pull/150
The current workaround is to use username / password to log in, are you using apikey secretkey in your cmk for calling the API ?

**Comment by hoogenm** [comment]
Yes, I did use the apikey/secretkey. Thank you for adding this to the 6.5.0 milestone.

**Comment by rohityadavcloud** [comment]
@hoogenm for now, the workaround is you can use username-password as auth for a cmk profile. #150 fixes your issue, I hit the same yesterday.

**Comment by rohityadavcloud** [comment]
Fixed by https://github.com/apache/cloudstack-cloudmonkey/pull/150
