### ISSUE TITLE
compilation error: fix gopath/goroot variables in Makefile

### ISSUE THREAD

**Issue by dhlaluku** [apache/cloudstack-cloudmonkey#18]
I gave it a try and realized that the code does not compile out-of-box from checkout as explained in the instructions.

`dingane@dingane-GL553VD:~/apache/cloudstack-cloudmonkey$ make run
▶  Running gofmt…
▶  Setting GOPATH…
▶  Building executable…
▶  Done!
cmk.go:24:2: cannot find package "cloudmonkey/cli" in any of:
	/usr/lib/go-1.10/src/cloudmonkey/cli (from $GOROOT)
	/home/dingane/go/src/cloudmonkey/cli (from $GOPATH)
cmk.go:25:2: cannot find package "cloudmonkey/config" in any of:
	/usr/lib/go-1.10/src/cloudmonkey/config (from $GOROOT)
	/home/dingane/go/src/cloudmonkey/config (from $GOPATH)
Makefile:38: recipe for target 'all' failed
make: *** [all] Error 1`

I was however able to compile and run after manually setting the $GOPATH to the current directory, viz. `export GOPATH=$PWD.`

**Comment by rhtyd** [comment]
@dhlaluku can you try again with latest master?

**Comment by dhlaluku** [comment]
I tried again on Ubuntu 18 and Fedora 28. The .dot directory does get created but the problem still remains the same.

**Comment by rhtyd** [comment]
@dhlaluku okay let me debug that will you later this week or next.

**Comment by DaanHoogland** [comment]
@dhlaluku I think #21 fixes this. Can you check (and close)?

**Comment by dhlaluku** [comment]
dingane@dingane-GL553VD:~/apache/cloudstack-cloudmonkey$ make all
▶  Running gofmt…
flag provided but not defined: -mod
usage: list [-e] [-f format] [-json] [build flags] [packages]
Run 'go help list' for details.
▶  Building executable… fc79e76
▶  Done!
flag provided but not defined: -mod
usage: build [-o output] [-i] [build flags] [packages]
Run 'go help build' for details.
Makefile:38: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by rhtyd** [comment]
@dhlaluku see README, use latest golang v1.11+
