### ISSUE TITLE
Autocomplete hangs for a long time

### ISSUE THREAD

**Issue by csquire** [apache/cloudstack-cloudmonkey#31]
Whenever I run a command and try to add a parameter, the autocomplete insists on looking up the available options.  This lookup can end up taking a very long time for large result sets.

<img width="350" alt="screen shot 2018-11-20 at 1 46 08 pm" src="https://user-images.githubusercontent.com/677724/48799080-e0de9580-eccb-11e8-8348-66ef74509930.png">

Steps to reproduce:
Start typing a command, for example, `list virtualmachines projectid=`.  After the `=` is typed, cmk attempts to retrieve the available options (I usually just want to use -1 as the project id). This sometimes hangs for me for over 15 seconds.  Then, if i start typing and backspace back to the `=` again...it fetches the options again and takes just as long! The above is just an example, it happens on other commands as well.

**Comment by pdion891** [comment]
did you run the command `sync` right after starting cloudmonkey ?

**Comment by csquire** [comment]
Yes, but `sync` only caches the API commands and parameters.  The delay is in the autocompletion of parameter values that appear to be auto-fetched after adding `=` to a parameter.

**Comment by rhtyd** [comment]
That's just the behaviour from the go prompt library. I'll explore what we can do. It's certainly doable to not show autocomplete options when your cursor goes back

**Comment by rhtyd** [comment]
@csquire I think you're uncomfortable with a new UX change where instead of pressing tab-tab for parameter completion, it gets kicked in when you type the `=`. I've already added the feature to disable parameter completion from #32. Due to the limitation of the cli library I'm using, the best I think we can manage is to only show the options when tab is pressed? Please checkout the latest master which fixes this.

**Comment by synergiator** [comment]
having this, I thought I add my comment here. In UI javascript autocomplete implementations, typically the lookup is activated only after you have provided some input like 3 chars. Especially in our case, looking up for an ID with zero input if there are dozens and more objects does not really make sense.

So maybe add an option to activate autocomplete lookup only after N chars input.  @rhtyd  what do you think?
