### ISSUE TITLE
Add option to disable autocomplete popup

### ISSUE THREAD

**Issue by csquire** [apache/cloudstack-cloudmonkey#32]
Feature Request:

After using `cmk` for awhile, I find the autocomplete popups provided by `go-prompt` to be quite distracting and would really like to just have tab completion. Any chance we can get an option to turn off the autocomplete popup while still having `tab` rotate through the available options?

**Comment by rhtyd** [comment]
I'll see if the library supports such an option. PRs are welcome.

**Comment by rhtyd** [comment]
The UX you're asking is not available in the library I've used; https://github.com/c-bata/go-prompt
I've however added a feature from python based cloudmonkey to disable parameter completion using the keyword: `set paramcompletion false`.
