### ISSUE TITLE
Variables in double quotes get passed with the double quotes (regression)

### ISSUE THREAD

**Issue by PaulAngus** [apache/cloudstack-cloudmonkey#34]
6.0.0 alpha 2
Previously, if a variable was passed in double quotes, the quotes were stripped. 
now they are included, causing failures 
```
svc_offering_id=`cloudmonkey list serviceofferings issystem=true name='System Offering For Software Router' | jq '.serviceoffering[].id'`

echo $svc_offering_id
"b1f32aa1-8d96-4d4c-a466-4287b63af19d"

 cloudmonkey create networkoffering name='Custom Simple Isolated Network Offering' displaytext='Offering for Isolated Network with only DHCP, DNS and User Data' networkrate=1024 guestiptype=Isolated specifyipranges=true specifyvlan=true supportedservices=Dhcp,Dns,UserData traffictype=Guest networkrate=1024 serviceproviderlist[0].provider=VirtualRouter serviceproviderlist[0].service=Dhcp serviceproviderlist[1].provider=VirtualRouter serviceproviderlist[1].service=Dns serviceproviderlist[2].provider=VirtualRouter serviceproviderlist[2].service=UserData serviceofferingid=**$svc_offering_id**

🙈 Error: (HTTP 431, error code 9999) Unable to execute API command createnetworkoffering due to invalid value. Invalid parameter serviceofferingid **value="b1f32aa1-8d96-4d4c-a466-4287b63af19d"** due to incorrect long value format, or entity does not exist or due to incorrect parameter annotation for the field in api cmd class.
```

**Comment by rhtyd** [comment]
Looks like this was a bug in older cloudmonkey, ideally the `jq` output would look something like `"some-uuid"`. Note the `svc_offering_id` will have quotes in its values. So, when the parameters is passed to cloudmonkey it is passed as `cloudmonkey some api somearg=\"some-uuid\"`. The newer cloudmonkey tries to allow the parameters passed as-is, and therefore passes the value with quotes. I've created a workaround for this in https://github.com/apache/cloudstack-cloudmonkey/commit/f3e09928f940bd2d17283f117bc61eef272670ea assuming normally people won't need to pass a string value with opening+closing quotes.

**Comment by rhtyd** [comment]
Fixed in https://github.com/apache/cloudstack-cloudmonkey/commit/f3e09928f940bd2d17283f117bc61eef272670ea closing.
