### ISSUE TITLE
variables in double or single quotes not passed

### ISSUE THREAD

**Issue by PaulAngus** [apache/cloudstack-cloudmonkey#37]
[root@ref-trl-844-k-M7-pangus-mgmt1 tmp]# service_offering_name="Ultra Tiny"
[root@ref-trl-844-k-M7-pangus-mgmt1 tmp]# cloudmonkey list serviceofferings name=$service_offering_name
[root@ref-trl-844-k-M7-pangus-mgmt1 tmp]# service_offering_name='Ultra Tiny'
[root@ref-trl-844-k-M7-pangus-mgmt1 tmp]# cloudmonkey list serviceofferings name=$service_offering_name
[root@ref-trl-844-k-M7-pangus-mgmt1 tmp]# cloudmonkey list serviceofferings name="Ultra Tiny"
{
  "count": 2,
  "serviceoffering": [
    {
      "cpunumber": 1,
      "cpuspeed": 500,
      "created": "2018-12-09T18:16:15+0000",
      "defaultuse": false,
      "displaytext": "Ultra Tiny - 1vCPU, 128MB RAM",
      "id": "c6ec88c5-504d-42b3-b864-b99fb95f5b9f",
      "iscustomized": false,
      "issystem": false,
      "isvolatile": false,
      "limitcpuuse": false,
      "memory": 128,
      "name": "Ultra Tiny",
      "offerha": true,
      "provisioningtype": "thin",
      "storagetype": "shared"
    },
    {
      "cpunumber": 1,
      "cpuspeed": 500,
      "created": "2018-12-09T18:17:29+0000",
      "defaultuse": false,
      "displaytext": "Ultra Tiny - 1vCPU, 128MB RAM",
      "id": "337cab06-2c81-4fba-983d-0da54a79734c",
      "iscustomized": false,
      "issystem": false,
      "isvolatile": false,
      "limitcpuuse": false,
      "memory": 128,
      "name": "Ultra Tiny",
      "offerha": true,
      "provisioningtype": "thin",
      "storagetype": "shared"
    }
  ]
}

cloudmonkey -d list serviceofferings name=$service_offering_name
[debug] cmdline args:[cloudmonkey -d list serviceofferings name=Ultra Tiny]
[debug] ExecCmd args: list, serviceofferings, name=Ultra, Tiny
[debug] NewAPIRequest API request URL:http://10.2.2.91:8080/client/api?apiKey=LIN6rqXuaJwMPfGYFh13qDwYz5VNNz1J2J6qIOWcd3oLQOq0WtD4CwRundBL6rzXToa3lQOC_vKjI3nkHtiD8Q&command=listServiceOfferings&name=Ultra&response=json&signature=Gjv8u3eaY2N%2FD8ZPrw1HIBlU%2F5g%3D
[debug] NewAPIRequest response status code:200
[debug] NewAPIRequest response body:{"listserviceofferingsresponse":{}}

**Comment by rhtyd** [comment]
@PaulAngus this is a bash limitation, whenever passing a variable always use double quotes `"`. I tried this with both new and old cloudmonkey and both had similar behaviours. For more information, please see https://unix.stackexchange.com/questions/131766/why-does-my-shell-script-choke-on-whitespace-or-other-special-characters

**Comment by PaulAngus** [comment]
thankyou Rohit, i understand what you are saying.  Thank you for investigating and explaining.
