### ISSUE TITLE
Should we support https://github.com/jmespath/go-jmespath for go based rewrite?

### ISSUE THREAD

**Issue by rohityadavcloud** [apache/cloudstack-cloudmonkey#45]
Enhancement:
Should we support https://github.com/jmespath/go-jmespath for go based rewrite?

**Comment by snifbr** [comment]
Hi @rhtyd I'm finally back and took some time to make this enhancement in golang as I promised.

I opened a new pull request #52 for this.

I hope this will be useful.

Sorry for any mistake I did, because it was my first contact with golang and I started this 2 weeks ago.

**Comment by rohityadavcloud** [comment]
Closing this, we've jq and other tools to do that. After much deliberation with some users and architects, we think the cmk tool should continue to be a simple CLI that can be bundled with other tools such as jq. Any changes like intelligent filtering etc may be implemented in the ACS mgmt server instead.
