### ISSUE TITLE
Status responses should not be formatted with %v

### ISSUE THREAD

**Issue by onitake** [apache/cloudstack-cloudmonkey#46]
When executing a command that returns a status response, such as `stop virtualmachine`, the response is logged as a simple dump of the Go data structure (like `fmt.Printf("%v")`), unless the JSON output format was selected.

Since these responses can contain nested data, it makes little sense to print them as a table, CSV or similar format, but the output produced by `%v` is very hard to read and barely useful for machine consumption.

Please either force JSON output or find a textual/tabular representation that makes sense for nested data structures. Maybe YAML output would be a good candidate?

**Comment by rhtyd** [comment]
The json is default output, I'll address this in future release. Thanks for reporting.
