### ISSUE TITLE
How to filter out not columns but results?

### ISSUE THREAD

**Issue by 1605200517** [apache/cloudstack-cloudmonkey#53]
I need to filter a subset of templates matching specific criteria.

Tried for example:

`cmk -o table -p admin list templates templatefilter=all  filter=id,name,zonename |grep "BUILD-47848"
`
This does not work well though because of the line breaks in the column "name".

How comes and what to do?

**Comment by rhtyd** [comment]
@1605200517 it's not a bug per say as table is probably for visual viewing and not meant for grepping/scripting purposes. Instead of table try the text or json output, and if you know the name of the template, try passing the keyword in the API itself like `list templates keyword=`.
