### ISSUE TITLE
How to create tags for uservm

### ISSUE THREAD

**Issue by pfienhold** [apache/cloudstack-cloudmonkey#54]
create tags resourcetype=uservm resourceids=93b527e7-6d8b-4b82-8a0b-87c5b7ef3fa8 tags='tag[0].key=aaa tag[0].value=444'
 Error: (HTTP 431, error code 9999) Unable to execute API command createtags due to invalid value tag[0].key=aaa tag[0].value=444 for parameter tags

create tags resourcetype=uservm resourceids=93b527e7-6d8b-4b82-8a0b-87c5b7ef3fa8 tags=???

**Comment by rhtyd** [comment]
@pfienhold this is a doc question, it's documented here:
https://github.com/apache/cloudstack-cloudmonkey/wiki/Usage#argument-passing
https://cwiki.apache.org/confluence/display/CLOUDSTACK/CloudStack+cloudmonkey+CLI#CloudStackcloudmonkeyCLI-Argumentpassing

Here is an example:
```
> create tags resourceids=1a9c598b-9957-4cd6-a0d3-b554cc022448 resourcetype=UserVm tags[0].key=someKey tags[0].value=someValue
```

Try with the latest 6.0 release (or the beta/RC), and report/reopen if you any issues;  https://github.com/apache/cloudstack-cloudmonkey/releases

**Comment by pfienhold** [comment]
With 6.1 RC it works like you said.
