### ISSUE TITLE
Listing default output always gives: Error on parsing and printing 'teal'

### ISSUE THREAD

**Issue by gerardjp** [apache/cloudstack-cloudmonkey#56]
Hi all,

I'm running into the error as mentioned in the description. Not sure where (what component or layer) this problem originates. It only occurs when output is `default` or `table`. When output is `json` it's ok.

The cmd/output:

```
(pce) 🐵 > list securitygroups
Error on parsing and printing 'teal'
count (pce) 🐵 > list users
Error on parsing and printing 'teal'
```

I'm running latest stable, installed as documented:

```
$ cat /etc/*release*
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=18.04
DISTRIB_CODENAME=bionic
DISTRIB_DESCRIPTION="Ubuntu 18.04 LTS"
NAME="Ubuntu"
VERSION="18.04 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04 LTS"
VERSION_ID="18.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic
```

Cloudmonkey version:
```
$ pip search cloudmonkey
cloudmonkey (5.3.3)  - Command Line Interface for Apache CloudStack
  INSTALLED: 5.3.3 (latest)
```

More info available. Thanks!.

**Comment by rhtyd** [comment]
@gerardjp I think your cloudmonkey config file is wrong, can you set the colour to false `set colour false`?

Also can you try and use the latest cloudmonkey (https://github.com/apache/cloudstack-cloudmonkey/releases) which is a complete new re-write in Go. The Python based cloudmonkey won't be maintained anymore.

**Comment by rhtyd** [comment]
Couldn't reproduce with latest cloudmonkey, kindly try with the latest Go-based 6.x release.

**Comment by 1605200517** [comment]
had this with 5.3.3 on Ubuntu as well - moving to 6.x! would be great to have it as Docker image #57
