### ISSUE TITLE
cmk 6 - Provide Docker file and publish to Docker hub

### ISSUE THREAD

**Issue by synergiator** [apache/cloudstack-cloudmonkey#57]
The latest version, 6.x seems unavailable as Docker image.

Last updated 3 years ago:
https://hub.docker.com/r/apache/cloudstack-cloudmonkey/

Feature request:
* add Dockerfile to build cmk
* publish Docker image to Docker hub

Example working Dockerfile:

```
FROM debian:sid as builder

WORKDIR /work/
RUN apt -y update && apt -y install git golang-go build-essential &&\
    git clone https://github.com/apache/cloudstack-cloudmonkey.git &&\
    go version &&\
    cd cloudstack-cloudmonkey &&\
    git checkout tags/6.0.0 &&\
    make all &&\
    pwd &&\
    ls -alh ./bin/cmk

FROM debian:stable
COPY --from=builder /work/cloudstack-cloudmonkey/bin/cmk /usr/bin/
RUN apt-get -y update && uname -a && mkdir -p /root/.cmk/ &&\
    cmk version && cmk help && ls -alh /root/

```

**Comment by rhtyd** [comment]
Thanks @1605200517 I've added the dockerfile now: https://github.com/apache/cloudstack-cloudmonkey/commit/b040e85d70b8570f2542f56ccff37550463d24b8

However, I've no clue who has access to push at dockerhub. Anybody know - @wido @GabrielBrascher @PaulAngus @DaanHoogland @swill @pdion891 ?

**Comment by rhtyd** [comment]
@synergiator https://hub.docker.com/r/apache/cloudstack-cloudmonkey/builds is available now

**Comment by synergiator** [comment]
@rhtyd hurray! Thank you.

Though it would be good also to have a tag with explicit version number.
