### ISSUE TITLE
Provide an option to disable line wrapping in table mode

### ISSUE THREAD

**Issue by 1605200517** [apache/cloudstack-cloudmonkey#58]
In table mode, line wrapping is sometimes undesired.

Current output example:
```

+--------------------------------+
|              NAME              |
+--------------------------------+
| Ubuntu18.04 bionic master      |
| BUILD-47876                    |
```

Provide an option to suppress line wrapping and enable output like:
```

+----------------------------------------+
|              NAME                      |
+----------------------------------------+
| Ubuntu18.04 bionic master BUILD-47876  |
```

**Comment by rhtyd** [comment]
@1605200517 it's hard to determine if line splitting is needed or not, ultimately as long as the information is visually available it serves the purpose for the table output. The text, json output are more suitable for such things (not break lines) to grep etc.
