### ISSUE TITLE
(#54) create tags not work

### ISSUE THREAD

**Issue by pfienhold** [apache/cloudstack-cloudmonkey#60]
(ibkcloud) 🐱 > version
Apache CloudStack 🐵 CloudMonkey 6.0.0

(ibkcloud) 🐱 > create tags resourceids=efc9796e-9cef-42b6-a6f8-4e9cd5bffcbd resourcetype=UserVm tags[0].key=someKey tags[0].value=someValue

💩 Missing required parameters:  tags

**Comment by rhtyd** [comment]
@pfienhold thanks, sorry about this - this has been already fixed in master and will be fixed in the next release. For now, you can use the RC1 test binaries that has this fixed:
https://github.com/apache/cloudstack-cloudmonkey/releases/tag/pre-next-rc
