### ISSUE TITLE
cmk add resourcedetail

### ISSUE THREAD

**Issue by forquesato** [apache/cloudstack-cloudmonkey#64]
Hello.

The command "add resourcedetail" works on cloudmonkey 5.3.3, but not on cloudMonkey 6.0.0 (cmk).

$ cmk add resourcedetail resourcetype=UserVm resourceid=5534 details[0].key=nicAdapter details[0].value=Vmxnet3
💩 Missing required parameters:  details

$ cloudmonkey add resourcedetail resourcetype=UserVm resourceid=5534 details[0].key=nicAdapter details[0].value=Vmxnet3

{
  "accountid": "7cab3d17-1093-11e7-8430-ae828600367e",
  "cmd": "org.apache.cloudstack.api.command.user.volume.AddResourceDetailCmd",
  "created": "2020-06-01T11:00:22-0300",
  "jobid": "d510ceeb-bd8c-4524-b346-f9007a82e1e6",
  "jobprocstatus": 0,
  "jobresult": {
    "success": true
  },
  "jobresultcode": 0,
  "jobresulttype": "object",
  "jobstatus": 1,
  "userid": "6e5b9999-5fab-43be-9d6e-35abf8f49792"
}
$ cmk list resourcedetails resourceid=5534 resourcetype=UserVm key=nicAdapter                                        {
  "count": 1,
  "resourcedetail": [
    {
      "fordisplay": true,
      "key": "nicAdapter",
      "resourceid": "5534",
      "resourcetype": "UserVm",
      "value": "Vmxnet3"
    }
  ]
}

**Comment by rhtyd** [comment]
Thanks @forquesato we've actually had this fixed, you can take cmk RC build for the next release here which fixes this issue: https://github.com/apache/cloudstack-cloudmonkey/releases/tag/pre-next-rc

My plan is to work on the next release soon where the fix will be generally available to users. Thanks for reporting.

**Comment by forquesato** [comment]
Thank you!
Best regards.
