### ISSUE TITLE
Error 432 while list publicipaddresses

### ISSUE THREAD

**Issue by weizhouapache** [apache/cloudstack-cloudmonkey#66]
see below
```
(local) 🐵 > list publicipaddresses associatednetworkid=Error 432: The given command:listNetscalerLoadBalancerNetworks does not exist or it is not available for user with id:null
```

**Comment by rhtyd** [comment]
Thanks for reporting @weizhouapache can you set debug on and run this. Is this on latest cmk? 

We probably can get of the heuristic to use any if the related APIs.

**Comment by weizhouapache** [comment]
@rhtyd cannot reproduce the issue in 6.1.0
however, there is still no network available for associatednetworkid
