### ISSUE TITLE
Name resolution doesn't work correctly on Darwin build

### ISSUE THREAD

**Issue by mlsorensen** [apache/cloudstack-cloudmonkey#67]
There's a known problem with Golang's net DNS code that keeps name resolution from working properly on Mac.  Golang binaries compiled for Mac only utilize /etc/resolv.conf, and not the Mac's dynamic, native name resolution libraries.

This is resolved generally by compiling with CGO_ENABLED=1, but you also have to be compiling the Darwin binary on a Mac in order to get it to work.

Users who want a functioning Darwin build of cloudmonkey will need to compile it themselves, enabling CGO, unless the project can produce such binaries and publish them.

See https://github.com/golang/go/issues/31705

**Comment by rhtyd** [comment]
@mlsorensen thanks for sharing, we build cmk with the CGO flag disabled: https://github.com/apache/cloudstack-cloudmonkey/blob/master/Makefile#L29 Do you know this bug status with the latest Go v1.14.x release?

If you've tested this on Darwin, I can setup a job or note to ensure we build on Darwin while publishing release binaries via Github releases.

**Comment by rhtyd** [comment]
@mlsorensen can you test https://github.com/apache/cloudstack-cloudmonkey/releases/tag/6.1.0 I've uploaded cmk binary built on OSX with `CGO_ENABLED=1` and close this issue on confirmation. Thanks.

**Comment by mlsorensen** [comment]
confirmed.

**Comment by mlsorensen** [comment]
confirmed.
