### ISSUE TITLE
Check for local profile also if localcloud is missing

### ISSUE THREAD

**Issue by ravening** [apache/cloudstack-cloudmonkey#69]
In earlier cloudmonkey, the default is profile is `local` and if we use the same config with `cmk` then it fails as it looks for `localcloud` in config file. It should work with either `localcloud` or `local` as default profile name to preserve backward compatibility

```
() 🐱 > list zones
Please provide either apikey/secretkey or username/password to make an API call
🙈 Error: failed to authenticate to make API call
() 🐱 >
```

explicitly mentioning `local` works

```
# cmk -p local
Apache CloudStack 🐵 CloudMonkey 6.1.0
Report issues: https://github.com/apache/cloudstack-cloudmonkey/issues

(local) 🐱 > list zones
{
  "count": 1,
  "zone": [
    {
      "allocationstate": "Enabled",
      "dhcpprovider": "VirtualRouter",
      "dns1": "8.8.8.8",
      "guestcidraddress": "192.168.10.0/24",
      "id": "8ae93aed-7db1-4a1a-9030-db0efac6ba62",
      "internaldns1": "8.8.4.4",
      "localstorageenabled": false,
      "name": "mgt122-10",
      "networktype": "Advanced",
      "securitygroupsenabled": false,
      "tags": [],
      "zonetoken": "09-97f3-34cf-bba1-5fc23fcb"
    }
  ]
}
(local) 🐱 >
```

**Comment by Pearl1594** [comment]
Currently, a localcloud profile is automatically created if not present by default. Moving this to the next milestone.

**Comment by rhtyd** [comment]
@ravening I think somewhere in notes/MLs we had discussed this. @Pearl1594 consider for 6.2.0 if the fix is simple (i.e. if localcloud is not availble fallback to local if available; or simply - throw an error that profile not found or something).

**Comment by shwstppr** [comment]
@ravening @rhtyd @Pearl1594 
Release before 6.0 used to use profiles and other configs from `.cloudmonkey` subdir in HOME directory. With 6.0 it started using `.cmk` subdir. And not just the profile none of other configurations (output format, etc) will be used by newer install. Personally, I don't see a point in checking old config now.
Also, both installs live as a separate program.
I would suggest we add a note in release notes/documentation that operator will have to re-add profiles if upgrading from cloudmonkey 5.3.3 or below.

**Comment by rhtyd** [comment]
Agree with @shwstppr 's comment, unless you've manually copied the old config file you won't hit this @ravening - I propose you start fresh and manually migrate your profiles to the new `cmk`. Please re-open if not satisfied.
