### ISSUE TITLE
migrate systemvm virtualmachine= lists guest vms instead of systemvms

### ISSUE THREAD

**Issue by borisstoyanov** [apache/cloudstack-cloudmonkey#72]
```
(localcloud) SBCM5> > migrate systemvm virtualmachineid=
7466da01-6fc0-4f31-bd30-dffc81fcb49f (shared)             80d5cb01-60f6-4991-959c-cd37ac4bd4d1 (vpc-vm)             b2f2f053-77a9-40a0-be1b-afe4b0c2f524 (isolated)
```

it would be great if it lists VRs and system vms instead of guest vms

**Comment by Pearl1594** [comment]
It's a good to have enhancement, however, may not be straight-forward, because of the heuristic approach used for auto completion, keeping it as part of 6.2.0 milestone for now.

**Comment by rohityadavcloud** [comment]
It's possible to add in specific heuristics for specific params of an API, that would be the only way to fix this. cc @nvazquez
