### ISSUE TITLE
create domain with "text" display, returns wrong format

### ISSUE THREAD

**Issue by andrijapanicsb** [apache/cloudstack-cloudmonkey#74]
CMK 6.1 - cmk set display text - lines returned are NOT in text format on "create", but instead a single line

[root@CSman ~]# cmk create domain name=Bootcamp999 networkdomain=bootcamp999.local
domain = {"haschild":false,"id":"6521008f-35bc-4195-ab06-f7710f38509a","level":1,"name":"Bootcamp999","networkdomain":"bootcamp999.local","parentdomainid":"fabe6af3-989f-11eb-a211-080027a86798","parentdomainname":"ROOT","path":"ROOT/Bootcamp999","secondarystoragetotal":0}

^^^ single line, instead of output in multiple lines, while JSON (see below) works fine.
(need to test other create API's with CMK 6.1 (ACS 4.15), but while using cloudmonkey 5.3.3 with ACS 4.11 these "create" commands returned multiple lines with "default" output (which, afaik, was "text"), so one could grep i.e.  "ID" from the result of the "create. ...' command.

[root@CSman ~]# cmk set display json
[root@CSman ~]# cmk create domain name=Bootcamp9999 networkdomain=bootcamp9999.local
{
  "domain": {
    "haschild": false,
    "id": "4ab43807-32c0-4883-a822-22d59292f08f",
    "level": 1,
    "name": "Bootcamp9999",
    "networkdomain": "bootcamp9999.local",
    "parentdomainid": "fabe6af3-989f-11eb-a211-080027a86798",
    "parentdomainname": "ROOT",
    "path": "ROOT/Bootcamp9999",
    "secondarystoragetotal": 0
  }
}

**Comment by Pearl1594** [comment]
@andrijapanicsb IMHO, when the display format is textual - the output format seems to be appropriate; adding newlines would basically make it identical to JSON format. Do you think pretty-printing the textual output (with newlines and indents) would be better?

**Comment by rhtyd** [comment]
@andrijapanicsb @Pearl1594 what was the behaviour with the legacy cloudmonkey? If there is a mismatch then we can attempt to fix, otherwise I would encourage to use json which is the new default in cmk.

**Comment by Pearl1594** [comment]
@rhtyd there is a difference in the way the textual output is displayed btw versions < 6.0.0 and newer versions, e.g., 
Text format output on cloudmonkey 5.3.3:
```
(local) 🐵 > create domain name=testDomain
domain:
id = 78cafb11-b627-4e78-8f0d-a04adbdda38c
name = testDomain
haschild = False
level = 1
parentdomainid = d83d7d66-ef91-11eb-adc6-1e00e8000282
parentdomainname = ROOT
path = ROOT/testDomain
secondarystoragetotal = 0.0

```

Whereas, output observed in cmk versions > v6
```
create domain name=testDomaincmk6
domain = map[haschild:false id:5e5f641e-3da6-41b2-b5d0-5aa9d343f0fa level:1 name:testDomaincmk6 parentdomainid:d83d7d66-ef91-11eb-adc6-1e00e8000282 parentdomainname:ROOT path:ROOT/testDomaincmk6 secondarystoragetotal:0]

```

We can add newlines to somewhat align to the old format - https://github.com/apache/cloudstack-cloudmonkey/pull/86
