### ISSUE TITLE
list templates doesn't work with variables

### ISSUE THREAD

**Issue by andrijapanicsb** [apache/cloudstack-cloudmonkey#75]
Not sure what is going on here...

[root@CSman bootcamp]# template_name="CentOS 5.6(64-bit) no GUI (XenServer)"
[root@CSman bootcamp]# cloudmonkey list templates name=$template_name templatefilter=all
[root@CSman bootcamp]#
[root@CSman bootcamp]# template_name='"CentOS 5.6(64-bit) no GUI (XenServer)"'
[root@CSman bootcamp]# cloudmonkey list templates name=$template_name templatefilter=all
[root@CSman bootcamp]#
[root@CSman bootcamp]# 
[root@CSman bootcamp]# cloudmonkey list templates name="CentOS 5.6(64-bit) no GUI (XenServer)" templatefilter=all filter=name,id
{
  "count": 1,
  "template": [
    {
      "id": "facab0c5-989f-11eb-a211-080027a86798",
      "name": "CentOS 5.6(64-bit) no GUI (XenServer)"
    }
  ]
}
[root@CSman bootcamp]# cloudmonkey version
Apache CloudStack  CloudMonkey 6.1.0

**Comment by andrijapanicsb** [comment]
When I renamed the template in DB from "CentOS 5.6(64-bit) no GUI (XenServer)" to "CentOS5.6(64-bit)noUI(XenServer)" (no spaces between words), then it worked fine 🤷

**Comment by andrijapanicsb** [comment]
The same goes for other commands e.g.:

[root@CSman bootcamp]# service_offering_name='"Ultra Tiny"'
[root@CSman bootcamp]# $cli list serviceofferings name=$service_offering_name
[root@CSman bootcamp]#
[root@CSman bootcamp]# service_offering_name="Ultra Tiny"
[root@CSman bootcamp]# $cli list serviceofferings name=$service_offering_name
[root@CSman bootcamp]#
[root@CSman bootcamp]#

**Comment by DaanHoogland** [comment]
I think you need to refer the var in quotes @andrijapanicsb . Seems to me to be a shell issue and not a cmk issue.

**Comment by andrijapanicsb** [comment]
Being lazy as I am (i.e. not gonna test it again), this is a variable, so why would you expect quotes are needed? It worked like that in cmk 5.3.3, but not now in 6.1.

**Comment by DaanHoogland** [comment]
Did it really @andrijapanicsb? The shell would always expand the var to include the spaces and than cmk would only get the first part as the value of the parameter. I don't think this was ever supposed to work without quotes. i.e. `cloudmonkey list templates name="$template_name" templatefilter=all` instead of `cloudmonkey list templates name=$template_name templatefilter=all` cmk has no control over CLI expansion/passing.

**Comment by andrijapanicsb** [comment]
Join the Bootcamp in May, and I can show you :) this is how it did work for last few years with CMK 5.3.3, we can take this offline if you want

**Comment by Pearl1594** [comment]
@andrijapanicsb I believe @DaanHoogland  is right wrt to using the variable in quotes. Tried reproducing the issue with cloudmonkey 5.3.3 and faced the same issue. 

```
[09:45:45] pearl@pearl-XPS-15-7590:~/go/src/github.com/cloudstack-cloudmonkey/cloudmonkey$ ./cloudmonkey.py --version
cloudmonkey 5.3.3
[09:45:49] pearl@pearl-XPS-15-7590:~/go/src/github.com/cloudstack-cloudmonkey/cloudmonkey$ 
[09:45:50] pearl@pearl-XPS-15-7590:~/go/src/github.com/cloudstack-cloudmonkey/cloudmonkey$ template_name="CentOS 5.6 (64-bit) no GUI (Simulator)"
[09:45:57] pearl@pearl-XPS-15-7590:~/go/src/github.com/cloudstack-cloudmonkey/cloudmonkey$ ./cloudmonkey.py  list templates name=$template_name templatefilter=all
[09:46:05] pearl@pearl-XPS-15-7590:~/go/src/github.com/cloudstack-cloudmonkey/cloudmonkey$ 
[09:46:05] pearl@pearl-XPS-15-7590:~/go/src/github.com/cloudstack-cloudmonkey/cloudmonkey$ 
[09:46:06] pearl@pearl-XPS-15-7590:~/go/src/github.com/cloudstack-cloudmonkey/cloudmonkey$ 
[09:46:06] pearl@pearl-XPS-15-7590:~/go/src/github.com/cloudstack-cloudmonkey/cloudmonkey$ ./cloudmonkey.py  list templates name="$template_name" templatefilter=all filter=name,id
count = 1
template:
id = cc0a3600-cf22-11eb-9edd-50eb7122da94
name = CentOS 5.6 (64-bit) no GUI (Simulator)

```

**Comment by weizhouapache** [comment]
agree with @DaanHoogland 
it looks like not a cmk issue.
it could be supported in cmk but maybe unnecessary.

**Comment by Pearl1594** [comment]
@andrijapanicsb Can you please advise if this is still relevant? Thanks

**Comment by rhtyd** [comment]
@andrijapanicsb I think it's the same with old cloudmonkey, have you tested that? It's better to use "$variable" when passing params to any cli.

**Comment by rhtyd** [comment]
I reviewed the issue, doesn't sound like a bug to me. @andrijapanicsb kindly re-open or discuss on dev@ if you're not satisfied. Thanks.
