### ISSUE TITLE
Unable to use new syncStoragePool API

### ISSUE THREAD

**Issue by shwstppr** [apache/cloudstack-cloudmonkey#81]
Newly added `syncStoragePool` API doesn't work with Cloudmonkey 6.1.0. Instead of firing API it synchronizes API cache. Even while trying to get docs for the API it does the same.

![cmk-sync](https://user-images.githubusercontent.com/153340/124229531-6638b080-db2b-11eb-9205-4dd3381fcccf.gif)

**Comment by harikrishna-patnala** [comment]
@shwstppr here the auto completion API works fine, but when we actually run the command, it is ignoring the parameters after 'sync'

If we run the API with full name it works fine,
(localcloud) SBCM5> > **syncStoragePool** id=37cf387a-ea2f-3456-a98a-03bc282072fd
{
  "storagepool": {
    "clusterid": "0c29f733-575b-4e6c-b7ff-9d595fc5bfb1",
    "clustername": "p1-c1",
    "created": "2021-05-11T15:51:13+0000",
    "disksizeallocated": 0,
    "disksizetotal": 2197949513728,
    "disksizeused": 1538292695040,
    "id": "37cf387a-ea2f-3456-a98a-03bc282072fd",
    "ipaddress": "10.0.32.142",
    "name": "DC",
    "overprovisionfactor": "2.0",
    "path": "/Trillian/DC",
    "podid": "d67d81d9-0235-4fb4-961e-0bd276776363",
    "podname": "Pod1",
    "provider": "DefaultPrimary",
    "scope": "CLUSTER",
    "state": "Up",
    "type": "DatastoreCluster",
    "zoneid": "4d21cd93-2bf4-46ab-99ed-d4e9d723591b",
    "zonename": "ref-trl-873-v-M7-vladimir-petrov"
  }
}

But yes, we need to fix this
