### ISSUE TITLE
Disable auto-complete option

### ISSUE THREAD

**Issue by serverchief** [apache/cloudstack-cloudmonkey#90]
In large env with many thousand assets, if I tab by mistake for autocompletion - it will take very long time to respond. 

Please kindly provide an ability to disable auto-complete altogether.

**Comment by rhtyd** [comment]
We used to have an option earlier to disable parameter completion, I suppose you still want autocompletion but not for resource uuid/ids.

**Comment by rhtyd** [comment]
@serverchief please test latest main and re-open if not satisfied with the fix from #91
