### ISSUE TITLE
Auto-complete not working for 'id' param in update storagecapabilities

### ISSUE THREAD

**Issue by sureshanaparti** [apache/cloudstack-cloudmonkey#98]
Auto-complete not working for 'id' param in update storagecapabilities

Tested with CloudMonkey 6.2.0 (build: 8aae61e).

```
(cloudcmk) > update storagecapabilities 
filter= id= 
(cloudcmk) > update storagecapabilities id=
```

**Comment by Pearl1594** [comment]
@sureshanaparti We could probably look at improving this in the next release of cmk - however, the reason behind this behavior is that when CloudMonkey tries to find the most appropriate list API that can be used to populate the values of `id` - it finds more than one, and hence, doesn't autocomplete the argument's values. For exapme: this is what is seen in debug mode:
```
(test) 🐱 > update storagecapabilities id=l[debug] Possible related noun for the arg: storagecapabilitiess and type: uuid
[debug] Finding possible API that have: id related APIs: [cancelStorageMaintenance createStoragePool enableStorageMaintenance findStoragePoolsForMigration syncStoragePool updateStorageCapabilities]
[debug] Found possible API: listCAProviders
[debug] Found possible API: listHostHAProviders
[debug] Found possible API: listNetworkServiceProviders
[debug] Found possible API: listStorageProviders
(test) 🐱 > update storagecapabilities id=

```

**Comment by rhtyd** [comment]
@sureshanaparti was this working with previous versions of cmk, say 6.1.0?

**Comment by Pearl1594** [comment]
No @rhtyd didn't work in the older versions too:
```
[root@ref-trl-1725-v-M7-pearl-dsilva-mgmt1 ~]# cmk
Apache CloudStack 🐵 CloudMonkey 6.0.0
Report issues: https://github.com/apache/cloudstack-cloudmonkey/issues

(localcloud) SBCM5> > 
(localcloud) SBCM5> > 
(localcloud) SBCM5> > update storagecapabilities id=


```

**Comment by sureshanaparti** [comment]
> @sureshanaparti was this working with previous versions of cmk, say 6.1.0?

doesn't work with 6.1.0 @rhtyd
