### ISSUE TITLE
New flag "-c" in cmk 6.2.0

### ISSUE THREAD

**Issue by sureshanaparti** [apache/cloudstack-cloudmonkey#99]
Noticed a new flag "-c" (different config file path) in CloudMonkey 6.2.0, which is not mentioned in the release notes here: https://github.com/apache/cloudstack-cloudmonkey/releases/tag/6.2.0. If it is supported , please update the release notes.

```
Allowed flags:
  -h        Show this help message or API doc when specified after an API
  -v        Print version
  -o        API response output format: json, text, table, column, csv
  -p        Server profile
  -d        Enable debug mode
  -c        different config file path
```

**Comment by rhtyd** [comment]
I think it may be supported since previous versions, @Pearl1594 to check and confirm

**Comment by Pearl1594** [comment]
No @rhtyd  - this was a new flag - but I guess the PR had no milestone attached - hence it slipped pass my attention.
I've updated the release notes: https://github.com/apache/cloudstack-cloudmonkey/releases/tag/6.2.0 
And the wiki: https://github.com/apache/cloudstack-cloudmonkey/wiki/Getting-Started#getting-help 
Thanks @sureshanaparti

**Comment by sureshanaparti** [comment]
> No @rhtyd - this was a new flag - but I guess the PR had no milestone attached - hence I probably missed adding it to the list of changes made.
> I've updated the release notes: https://github.com/apache/cloudstack-cloudmonkey/releases/tag/6.2.0
> And the wiki: https://github.com/apache/cloudstack-cloudmonkey/wiki/Getting-Started#getting-help
> Thanks @sureshanaparti

Thanks @Pearl1594 , for the quick turnaround!

**Comment by soreana** [comment]
@sureshanaparti It was added by me in: https://github.com/apache/cloudstack-cloudmonkey/pull/70

**Comment by soreana** [comment]
@Pearl1594 Could you please update the wiki and release note once again. 🙈 
I fixed the capitalization in `different config file path` in https://github.com/apache/cloudstack-cloudmonkey/pull/101

**Comment by rhtyd** [comment]
Seems release notes were updated and wiki.
